name: Test and Deploy

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Login
              uses: docker/login-action@v3
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - uses: actions/checkout@v3
            - name: Build and push Docker image
              uses: docker/build-push-action@v6.18.0
              with:
                  secrets: hf_token=${{ secrets.HF_TOKEN }}
                  context: .
                  push: true
                  tags: 'hapnan/whisperx-worker:${{ github.sha }}'

            - name: Run Tests
              uses: runpod/test-runner@v2.1.0
              with:
                  image-tag: 'hapnan/whisperx-worker:${{ github.sha }}'
                  runpod-api-key: ${{ secrets.RUNPOD_API_KEY }} # Add your API key to a GitHub secret
                  test-filename: .github/tests.json
                  request-timeout: 300
